### PR TITLE
Fixed Dashed Line

### LINKED ISSUE #157: Route list item overflow occasionally
I noticed it happening on list items with delays, when navigating quickly to the list before the network request has finished fetching.

image

### PR DESCRIPTION
**Pull request by planecore**
Closes #157

### CODE REVIEW

File: app/screens/route-list/route-list-screen.tsx [hunk 1]
```diff
@@ -52,6 +54,18 @@ export const RouteListScreen = observer(function RouteListScreen({ navigation, r
...
+    const { width: deviceWidth } = Dimensions.get("screen")
+    const allTexts = flatMap(trains.data ?? [], ({ delay, duration }) => [
+      delay > 0 ? (delay + " " + translate("routes.delayTime")).length : 0,
+      duration.length,
+    ])
+    const maxTextLength = max(allTexts)
+    const shouldShowDashedLineByTextLength = round(deviceWidth / fontScale / 30) >= maxTextLength
+
+    return fontScale <= 1.2 && deviceWidth >= 360 && shouldShowDashedLineByTextLength
+  }, [trains.data])
```
Comment (guytepper) [inline app/screens/route-list/route-list-screen.tsx:67]: Add comments

**Review by guytepper — APPROVED** [review]
