### PR TITLE
Fix android modals overflowing outside the viewport

### LINKED ISSUE #382: Replace `react-native-modal` with `react-native-modalfy`
Since `react-native-modal` isn't maintained anymore, we get warnings on Android related to it's reanimated usage. 

Let's replace it with [`react-native-modalfy`](https://github.com/colorfy-software/react-native-modalfy), which is a maintained library, and offers better performance and features.

### PR DESCRIPTION
**Pull request by guytepper**
Replaced `react-native-modal` library with `react-native-modalfy`. 
Resolves #382.

### CODE REVIEW

File: app/screens/settings/settings-tip-jar-screen.tsx [hunk 1]
```diff
@@ -121,7 +121,8 @@ export const TipJarScreen = observer(function TipJarScreen() {
       const purchase = (await requestPurchase(requestPurchaseParams)) as ProductPurchase
 
       await finishTransaction({ purchase, isConsumable: true })
-      setModalVisible(true)
+      alert("open modal")
```
Comment (planecore) [inline app/screens/settings/settings-tip-jar-screen.tsx:124]: is it still needed? check if I missed another one too please

File: app/screens/settings/settings-tip-jar-screen.tsx [hunk 2]
```diff
@@ -140,6 +141,7 @@ export const TipJarScreen = observer(function TipJarScreen() {
 
       settings.addTip(Number(amount))
     } catch (err) {
+      console.error(err)
```
Comment (planecore) [inline app/screens/settings/settings-tip-jar-screen.tsx:144]: delete please :)

**Review by planecore — CHANGES_REQUESTED** [review]
Just a few comments

**Review by planecore — APPROVED** [review]
